let tripDays = [
  ["2026-09-06","田尻町 → 京都市","京都",[["12:40","關西機場","抵達關西，辦理入境與取車。"],["16:17","Guest House Kyoan","京都住宿，放下行李後再出發。"],["17:29","伏見稻荷大社","傍晚走進千本鳥居，留一些時間慢慢拍照。"],["18:40","Guest House Kyoan","回住宿休息。"]]],
  ["2026-09-07","京都府 → 京都市","京都",[["07:00","Guest House Kyoan","早起出發，避開東山人潮。"],["07:29","清水寺","先看本堂與音羽瀑布。"],["09:39","二年坂／三年坂","沿著石坂街景慢慢逛。"],["10:53","祇園花見小路","町家街景，請保持安靜通行。"],["11:37","錦市場","午餐與京都小吃。"],["13:06","Guest House Kyoan","回去休息。"],["15:07","京都鐵道博物館","結束後可到梅小路公園玩遊樂設施。"],["19:13","Guest House Kyoan","回住宿。"]]],
  ["2026-09-08","高島市 → 福井縣","若狹",[["09:00","Guest House Kyoan","離開京都，前往湖西。"],["09:53","白鬚神社","琵琶湖上的鳥居。"],["11:05","琵琶湖兒童之國公園","中午野餐；先到超市買東西。"],["13:00","若狹漁人碼頭","海鮮午餐。"],["14:33","Party&Resort ZERO'sHOUSE","小濱住宿。"],["15:35","小濱市三丁町歷史街區","老街散步。"]]],
  ["2026-09-09","京都府 → 宮津市 → 小濱市","宮津",[["09:00","Party&Resort ZERO'sHOUSE","出發往海之京都。"],["09:51","舞鶴港海鮮市場","海鮮市場早午餐。"],["13:11","伊根浦觀光案內","舟屋聚落資訊與停車。"],["14:32","天橋立傘松公園","搭纜車眺望天橋立。"],["15:51","智恩寺","文殊信仰寺院。"],["16:56","道之驛 京都 by the Sea MIYAZU","補給與伴手禮。"],["17:59","KYOTO TANGO MIYAZU inn","宮津住宿。"]]],
  ["2026-09-10","箕面市 → 西成區","大阪",[["08:00","KYOTO TANGO MIYAZU inn","離開宮津。"],["08:52","休息站","補給與休息。"],["10:51","勝尾寺","達摩與勝運信仰。"],["11:58","箕面大瀧","山林瀑布散步。"],["13:31","Costco 好市多門真倉庫店","採買補貨。"],["15:02","鹿の宿","大阪住宿。"]]],
  ["2026-09-11","西成區 → 港區","大阪",[["08:00","鹿の宿","早餐後出發。"],["09:20","木津市場","市場早餐。"],["10:59","海遊館","看海洋生物。"],["13:32","帆船型觀光船 聖瑪麗亞號","港區水上行程。"],["14:34","天保山大摩天輪","港景與天空。"],["15:52","空庭溫泉","泡湯休息。"],["19:31","鹿の宿","回住宿。"]]],
  ["2026-09-12","西成區 → 浪速區","大阪",[["08:00","鹿の宿","出發。"],["08:48","大阪城","城跡與公園。"],["10:26","大阪城御座船乘船處","護城河遊船。"],["11:31","難波八阪神社","巨型獅子殿。"],["12:51","心齋橋筋商店街","購物與午餐。"],["14:55","道頓堀水上觀光船","已預約 20:00–20:30；日本橋站 6 號出口步行約 5 分鐘。"],["16:23","鹿の宿","回住宿。"]]],
  ["2026-09-13","阿倍野區 → 天王寺區","大阪",[["08:00","鹿の宿","出發。"],["09:28","大阪市天王寺動物園","親子動物園。"],["11:04","通天閣","新世界地標。"],["12:17","Harukas 300 Helipad","高空展望。"],["13:30","鹿の宿","回住宿。"]]],
  ["2026-09-14","北區 → 西成區","大阪",[["08:00","鹿の宿","出發。"],["09:41","梅田藍天大廈 空中庭園展望台","城市景觀。"],["10:42","HEP FIVE 摩天輪","紅色摩天輪。"],["11:21","天神橋筋商店街","在地商店街。"],["12:31","大阪生活今昔館","室內街景博物館。"],["14:36","扇町公園","休息與遊玩。"],["16:11","玉出超市 天神橋店","採買。"],["17:29","鹿の宿","回住宿。"]]],
  ["2026-09-15","西成區 → 此花區","大阪",[["05:05","鹿の宿","早起準備。"],["06:16","日本環球影城","全天 USJ 行程。"]]],
  ["2026-09-16","西成區 → 田尻町","關西",[["08:00","鹿の宿","收拾行李。"],["09:35","關西機場站","搭車前往機場。"]]],
].map(([date, area, weather, stops], index) => ({ day:index + 1, date, area, weather, stops }));

let flights = [{ code:"AK170", label:"去程", date:"2026 / 09 / 06", time:"08:30-12:40", from:"高雄", to:"關西" },{ code:"BR181", label:"回程", date:"2026 / 09 / 16", time:"12:10–14:30", from:"關西", to:"高雄" }];
let bookings = [["航班","AK170","9/06 去程 · 12:40 抵達關西","fa-solid fa-plane-departure"],["航班","BR181","9/16 回程 · 12:10–14:30","fa-solid fa-plane-arrival"],["住宿","Guest House Kyoan","9/06–9/08 · 京都","fa-solid fa-bed"],["住宿","Party&Resort ZERO'sHOUSE","9/08 · 小濱","fa-solid fa-bed"],["住宿","KYOTO TANGO MIYAZU inn","9/09 · 宮津","fa-solid fa-bed"],["住宿","鹿の宿","9/10–9/15 · 大阪西成","fa-solid fa-bed"],["票券","道頓堀水上觀光船","9/12 20:00–20:30","fa-solid fa-ticket"],["票券","日本環球影城","9/15 · 入園日前確認票券","fa-solid fa-star"]];
const listGroups = [["出發前",["護照與簽證","旅平險證明","網卡／eSIM","日圓與信用卡"]],["行李",["充電器與行動電源","雨具","常備藥","兒童用品"]],["行程",["USJ 票券","住宿聯絡方式","租車文件","道頓堀遊船集合點"]]];
let planningLists = { todo:["確認 USJ 入園與快速通關","補上租車駕照與保險文件","確認道頓堀遊船集合點","通知住宿抵達時間"], packing:["護照、駕照與信用卡","行動電源與充電線","雨具與折傘","常備藥與兒童用品"], shopping:["日圓現金","日本網卡／eSIM","零食與保溫瓶","旅遊收納袋"] };
const initial = JSON.parse(localStorage.getItem("osaka-travel-state") || "{}");
const state = { section:"itinerary", day:Number(initial.day) || 1, done:initial.done || {}, tasks:initial.tasks || {}, expenses:initial.expenses || [], journal:initial.journal || [], planningTab:initial.planningTab || "todo" };
let syncedBookings = initial.bookings || null;
const app = document.querySelector("#app-content");
const safe = (text) => String(text).replace(/[&<>'"]/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"})[char]);
const icon = (classes) => `<i class="${classes}" aria-hidden="true"></i>`;
const categoryIcon = (category) => ({餐飲:"fa-solid fa-utensils",交通:"fa-solid fa-train-subway",門票:"fa-solid fa-ticket",購物:"fa-solid fa-bag-shopping",住宿:"fa-solid fa-bed"}[category] || "fa-solid fa-receipt");
let syncTimer;
const applyBookingData = (data) => {
  if (!data || typeof data !== "object") return;
  syncedBookings = data;
  const sourceFlights = Array.isArray(data.flights) ? data.flights : data.flight ? [data.flight] : [];
  if (sourceFlights.length) {
    flights = sourceFlights.map((flight, index) => ({
      code: flight.code || "",
      label: flight.label || (index === 0 ? "去程" : "回程"),
      date: String(flight.date || "").replace(/-/g, " / "),
      time: [flight.departure, flight.arrival].filter(Boolean).join("-"),
      from: flight.from || flight.fromCode || "",
      to: flight.to || flight.toCode || "",
    }));
  }
  const stayItems = Array.isArray(data.stays) ? data.stays : [];
  const voucherItems = Array.isArray(data.vouchers) ? data.vouchers : [];
  bookings = [
    ...flights.map((flight) => ["航班", flight.code, `${flight.date} ${flight.label}`, flight.label === "回程" ? "fa-solid fa-plane-arrival" : "fa-solid fa-plane-departure"]),
    ...stayItems.map((stay) => ["住宿", stay.name, stay.detail || `${stay.checkIn || ""} · ${stay.location || ""}`, "fa-solid fa-bed"]),
    ...voucherItems.map((voucher) => ["票券", voucher.title, voucher.file || "", "fa-solid fa-ticket"]),
  ];
};
const applyTripContent = (data) => {
  if (!data || typeof data !== "object") return;
  if (Array.isArray(data.tripDays) && data.tripDays.length) tripDays = data.tripDays;
  if (data.planningLists && typeof data.planningLists === "object") planningLists = data.planningLists;
};
window.applyBookingData = applyBookingData;
window.applyTripContent = applyTripContent;
if (initial.tripDays || initial.planningLists) applyTripContent(initial);
if (syncedBookings) applyBookingData(syncedBookings);
const sharedData = () => ({ day:state.day, done:state.done, tasks:state.tasks, expenses:state.expenses, journal:state.journal, planningTab:state.planningTab, tripDays, planningLists, ...(syncedBookings ? { bookings:syncedBookings } : {}) });
const save = () => { const data = sharedData(); localStorage.setItem("osaka-travel-state", JSON.stringify(data)); clearTimeout(syncTimer); syncTimer = setTimeout(() => fetch("./api/state", { method:"PUT", headers:{ "Content-Type":"application/json" }, body:JSON.stringify({ data }) }).catch(() => {}), 700); };
const mapUrl = (place) => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(place)}`;
const money = (value) => new Intl.NumberFormat("zh-TW", { style:"currency", currency:"JPY", maximumFractionDigits:0 }).format(value || 0);
const dayText = (date) => { const value = new Date(`${date}T12:00:00`); return [value.getMonth() + 1, value.getDate(), new Intl.DateTimeFormat("zh-TW", { weekday:"short" }).format(value).replace("週", "")]; };
const daysUntil = () => Math.max(0, Math.ceil((new Date("2026-09-06T12:40:00+09:00") - Date.now()) / 86400000));

function itineraryPage() {
  const current = tripDays.find((item) => item.day === state.day);
  const completed = current.stops.filter((_, index) => state.done[`${current.day}-${index}`]).length;
  return `<section class="section itinerary-view"><div class="section-intro"><p>行程日期</p><button class="tiny-action" data-action="today" type="button">今天在哪裡？</button></div><div class="day-scroller" role="tablist" aria-label="選擇旅行日">${tripDays.map((item) => { const [date, month, weekday] = dayText(item.date); return `<button class="day-chip ${item.day === state.day ? "is-active" : ""}" data-day="${item.day}" role="tab" aria-selected="${item.day === state.day}" type="button"><small>DAY ${item.day}</small><strong>${date}/${month}</strong><em>${weekday}</em></button>`; }).join("")}</div><article class="weather-card"><div class="weather-card__cloud cloud-one"></div><div class="weather-card__cloud cloud-two"></div><div><p class="weather-place">${current.weather} · 旅行日天氣</p><h2>晴朗無雲 ${icon("fa-solid fa-sun")}</h2><p class="weather-note">出發前 7 天再確認即時預報與穿著。</p></div><div class="weather-degree"><b>26°</b><span>20° / 29°</span></div><div class="weather-facts"><span>${icon("fa-solid fa-umbrella")} 10%<small>降雨機率</small></span><span>${icon("fa-solid fa-wind")} 2 級<small>風力</small></span><span>${icon("fa-solid fa-sun")} 05:35<small>日出</small></span></div></article><article class="countdown-card"><span aria-hidden="true">${icon("fa-solid fa-plane-departure")}</span><div><small>距離出發</small><strong>${daysUntil()}<i>天</i></strong></div><p>大阪，我們要來了</p></article><div class="day-heading"><div><p>DAY ${current.day}</p><h2>${current.area}</h2><span>${current.date.replaceAll("-", ".")} · 已完成 ${completed}/${current.stops.length}</span></div><span class="day-orb">${current.day}</span></div><ol class="schedule-list">${current.stops.map(([time, place, note], index) => { const key = `${current.day}-${index}`; const done = state.done[key]; return `<li class="schedule-item ${done ? "is-done" : ""}"><button class="stop-check" data-action="stop" data-key="${key}" aria-label="${done ? "標記未完成" : "標記完成"}" type="button">${done ? icon("fa-solid fa-check") : ""}</button><time>${time}</time><div class="schedule-item__copy"><h3>${safe(place)}</h3><p>${safe(note)}</p><a href="${mapUrl(place)}" target="_blank" rel="noopener">在地圖開啟 ${icon("fa-solid fa-arrow-up-right-from-square")}</a></div></li>`; }).join("")}</ol></section>`;
}
function bookingPage() { const stays = bookings.filter(([type]) => type === "住宿"); const tickets = bookings.filter(([type]) => type === "票券"); return `<section class="section booking-view"><div class="page-title"><p>旅程收納</p><h2>我的預訂</h2><span>機票、住宿、租車與憑證都放在同一個地方。</span></div><div class="booking-summary"><span>已整理</span><strong>${bookings.length}<i>項</i></strong><p>出發前再核對一次訂單。</p></div><section class="booking-section"><div class="booking-section__title"><span>${icon("fa-solid fa-plane")}</span><h3>機票</h3><small>${flights.length} 段</small></div><div class="flight-stack">${flights.map((flight) => `<article class="boarding-pass"><div class="boarding-pass__main"><small>${flight.label} · ${flight.code}</small><div><strong>${flight.from}</strong>${icon("fa-solid fa-arrow-right")}<strong>${flight.to}</strong></div><p>${flight.date}</p></div><div class="boarding-pass__stub"><span>${flight.label.includes("去程") ? "抵達時間" : "起飛時間"}</span><b>${flight.time}</b><small>${flight.code}</small></div></article>`).join("")}</div></section><section class="booking-section"><div class="booking-section__title"><span>${icon("fa-solid fa-bed")}</span><h3>住宿</h3><small>${stays.length} 間</small></div><div class="stay-stack">${stays.map(([,name,detail],index) => `<article class="stay-card"><div class="stay-card__photo stay-card__photo--${index + 1}"><span>${icon("fa-solid fa-bed")}</span></div><div><h4>${name}</h4><p>${detail}</p><small>入住資訊與地址待補</small></div><button data-action="copy" data-name="${safe(name)}" type="button" aria-label="複製 ${safe(name)}">${icon("fa-solid fa-ellipsis")}</button></article>`).join("")}</div></section><section class="booking-section"><div class="booking-section__title"><span>${icon("fa-solid fa-car-side")}</span><h3>租車</h3></div><article class="rental-card"><div class="rental-card__car">${icon("fa-solid fa-car-side")}</div><div><h4>關西自駕</h4><p>取還車時間、車型、保險與 ETC</p><small>尚待補上預訂資訊</small></div><button type="button" disabled>待補</button></article></section><section class="booking-section"><div class="booking-section__title"><span>${icon("fa-solid fa-ticket")}</span><h3>憑證</h3><small>${tickets.length} 張</small></div><div class="voucher-list">${tickets.map(([,name,detail,iconClass]) => `<article><span>${icon(iconClass)}</span><div><h4>${name}</h4><p>${detail}</p></div><button data-action="copy" data-name="${safe(name)}" type="button" aria-label="複製 ${safe(name)}">查看</button></article>`).join("")}</div></section></section>`; }
function expensePage() { const total = state.expenses.reduce((sum, item) => sum + Number(item.amount), 0); return `<section class="section expense-view"><div class="page-title"><p>旅行帳本</p><h2>一起記帳</h2><span>預設日幣；先記下每筆花費，再一起分攤。</span></div><article class="expense-dashboard"><div><span>總支出</span><strong>${money(total)}</strong><small>JPY · 日本円</small></div><div class="expense-dashboard__ring"><b>${state.expenses.length}</b><small>筆紀錄</small></div><p>大阪 11 日旅行</p></article><div class="expense-switch" role="tablist" aria-label="記帳幣別"><button class="is-active" type="button" role="tab" aria-selected="true">${icon("fa-solid fa-yen-sign")} 日幣 JPY</button><button type="button" disabled role="tab" aria-selected="false">NT$ 台幣</button></div><form class="expense-form expense-form--compact" id="expense-form"><div class="expense-form__heading"><span>${icon("fa-solid fa-plus")}</span><h3>新增支出</h3></div><label class="amount-input">${icon("fa-solid fa-yen-sign")}<input name="amount" required type="number" min="1" inputmode="numeric" placeholder="0" autofocus /></label><label>項目<input name="item" required maxlength="36" placeholder="例如：錦市場午餐" /></label><div class="form-row"><label>類別<select name="category"><option>餐飲</option><option>交通</option><option>門票</option><option>購物</option><option>住宿</option></select></label><label>付款人<select name="payer"><option>張家嘉</option><option>全體</option></select></label></div><div class="split-row"><span>分攤對象</span><div><b>嘉</b><b>家</b><b>旅</b><small>全體均分</small></div></div><button class="primary-button" type="submit">記下這筆日幣支出</button></form><div class="ledger-title"><h3>最近支出</h3><span>${money(total)}</span></div><div class="ledger">${state.expenses.length ? state.expenses.slice().reverse().map((item) => `<article><span class="ledger-dot">${icon(categoryIcon(item.category))}</span><div><h4>${safe(item.item)}</h4><p>${safe(item.category)} · ${safe(item.payer || "張家嘉")} · JPY</p></div><strong>${money(item.amount)}</strong><button data-action="expense-delete" data-id="${item.id}" type="button" aria-label="刪除 ${safe(item.item)}">${icon("fa-solid fa-trash-can")}</button></article>`).join("") : `<div class="empty-state"><span>${icon("fa-solid fa-yen-sign")}</span><p>第一筆旅行支出，從這裡開始。</p></div>`}</div></section>`; }
function journalPage() { return `<section class="section"><div class="page-title"><p>旅行回憶</p><h2>今日手記</h2><span>照片會褪色，當下的心情不會。</span></div><form class="journal-compose" id="journal-form"><textarea name="note" required maxlength="180" placeholder="今天最想記住的是⋯⋯"></textarea><button class="primary-button" type="submit">留下這一頁</button></form><div class="journal-list">${state.journal.length ? state.journal.slice().reverse().map((item) => `<article class="journal-entry"><div class="journal-entry__stamp">${item.day}</div><div><p>${safe(item.note)}</p><span>${item.date}</span></div><button data-action="journal-delete" data-id="${item.id}" type="button" aria-label="刪除日誌">${icon("fa-solid fa-trash-can")}</button></article>`).join("") : `<div class="empty-state journal-empty"><span>${icon("fa-solid fa-feather-pointed")}</span><p>旅程還沒開始。<br />等第一個想留下的瞬間。</p></div>`}</div></section>`; }
function planningPage() { const tabs = [["todo","待辦清單","fa-solid fa-list-check"],["packing","行李清單","fa-solid fa-suitcase-rolling"],["shopping","採買清單","fa-solid fa-cart-shopping"]]; const tasks = planningLists[state.planningTab]; const done = tasks.filter((_,index) => state.tasks[`${state.planningTab}-${index}`]).length; return `<section class="section planning-view"><div class="page-title"><p>旅行準備</p><h2>慢慢打包</h2><span>把每件事分好類，旅行前不再手忙腳亂。</span></div><article class="planning-hero"><div><small>整體進度</small><strong>${Object.values(state.tasks).filter(Boolean).length}<i> / 12</i></strong><p>完成一件，離出發更近一點。</p></div><span>${icon("fa-solid fa-leaf")}</span></article><div class="planning-tabs" role="tablist" aria-label="準備清單類型">${tabs.map(([id,label,iconClass]) => `<button class="${id === state.planningTab ? "is-active" : ""}" data-action="planning-tab" data-tab="${id}" type="button" role="tab" aria-selected="${id === state.planningTab}"><span>${icon(iconClass)}</span>${label}</button>`).join("")}</div><section class="planning-list"><div class="planning-list__head"><div><p>${tabs.find(([id]) => id === state.planningTab)[1]}</p><h3>已完成 ${done} / ${tasks.length}</h3></div><span class="assignment">全體</span></div>${tasks.map((task,index) => { const key = `${state.planningTab}-${index}`; return `<button class="task ${state.tasks[key] ? "is-done" : ""}" data-action="task" data-key="${key}" type="button"><i>${state.tasks[key] ? icon("fa-solid fa-check") : ""}</i><span>${task}</span><em>全體</em></button>`; }).join("")}</section></section>`; }
function render() { const pages = { itinerary:itineraryPage, bookings:bookingPage, expenses:expensePage, journal:journalPage, planning:planningPage }; app.innerHTML = pages[state.section](); document.querySelectorAll(".bottom-nav__item").forEach((button) => button.classList.toggle("is-active", button.dataset.section === state.section)); }
document.querySelector(".bottom-nav").addEventListener("click", (event) => { const button = event.target.closest("[data-section]"); if (button) { state.section = button.dataset.section; render(); window.scrollTo({ top:0, behavior:"smooth" }); } });
app.addEventListener("click", (event) => { const button = event.target.closest("[data-action], [data-day]"); if (!button) return; if (button.dataset.day) { state.day = Number(button.dataset.day); save(); render(); return; } const { action,key,id,name } = button.dataset; if (action === "stop") { state.done[key] = !state.done[key]; save(); render(); } if (action === "task") { state.tasks[key] = !state.tasks[key]; save(); render(); } if (action === "expense-delete") { state.expenses = state.expenses.filter((item) => item.id !== id); save(); render(); } if (action === "journal-delete") { state.journal = state.journal.filter((item) => item.id !== id); save(); render(); } if (action === "copy") { navigator.clipboard?.writeText(name).catch(() => {}); button.textContent = "已複製"; } if (action === "today") { const index = tripDays.findIndex((item) => item.date === new Date().toISOString().slice(0,10)); state.day = index >= 0 ? tripDays[index].day : 1; save(); render(); } });
app.addEventListener("click", (event) => { const button = event.target.closest('[data-action="planning-tab"]'); if (!button) return; state.planningTab = button.dataset.tab; save(); render(); });
app.addEventListener("submit", (event) => { event.preventDefault(); const form = event.target; const data = new FormData(form); if (form.id === "expense-form") state.expenses.push({ id:crypto.randomUUID(), item:data.get("item"), amount:Number(data.get("amount")), category:data.get("category"), payer:data.get("payer") }); if (form.id === "journal-form") state.journal.push({ id:crypto.randomUUID(), note:data.get("note"), day:`DAY ${state.day}`, date:new Date().toLocaleDateString("zh-TW") }); save(); render(); });
if ("serviceWorker" in navigator) window.addEventListener("load", () => navigator.serviceWorker.register("./sw.js").catch(() => {}));
render();
fetch("./api/state").then((response) => response.ok ? response.json() : Promise.reject()).then(({ data }) => { if (!data || typeof data !== "object") return; state.day = Number(data.day) || state.day; state.done = data.done || state.done; state.tasks = data.tasks || state.tasks; state.expenses = Array.isArray(data.expenses) ? data.expenses : state.expenses; state.journal = Array.isArray(data.journal) ? data.journal : state.journal; applyTripContent(data); state.planningTab = planningLists[data.planningTab] ? data.planningTab : state.planningTab; if (data.bookings) { applyBookingData(data.bookings); } localStorage.setItem("osaka-travel-state", JSON.stringify(sharedData())); render(); }).catch(() => {});
